#!/bin/sh

if [ -z "$TERM" ]; then
    _term=linux
else
    _term=$TERM
fi

bold=$(tput -T $_term bold)
normal=$(tput -T $_term sgr0)

echo
echo "    ${bold}***** Warning *****${normal}"
echo
echo "    After changing your IP address, launch this command: ${bold}changeip-fogserver${normal}"
echo "    Unless executed, FOG Server will not work properly."
echo
echo "    ${bold}changeip-fogserver${normal} - Change the IP address inside FOG Server configuration"
echo "    ${bold}regencert-fogserver${normal} - Regen web certificates (used by FOG Client)"
echo "    ${bold}regensecret-fogserver${normal} - Regen all passwords used by FOG Server (FTP, web,...)"
